

export const BALTIKA_DB_TRANSLATER = {
  "Mat": 'Период',
  "Per_level": 'Период',
  "Fed_name": 'Период',
  "Category": 'Категория',
  "Segment_name": 'Период',
  "Segment": 'Период',
  "Brand": 'Бренд',
  "Subbrand": 'Бренд',
  "Ontrade_Offtrade": 'Бренд',
  "Channel": 'Канал',
  "Subchannel": 'Канал',
  "Chain": 'Сеть',
  "base_all": 'Сеть',
  "base_18": 'Сеть',
  "Penetration_base_all": 'Сеть',
  "Penetration_base_18": 'Сеть',
  "Penetration_base_base_category_buyers": 'Сеть',
  "Average_purchase_frequency": 'Сеть',
  "Avg_check": 'Сеть',
  "Avg_ltr_per_purch": 'Сеть',
  "Avg_qty_per_purch": 'Сеть',
  "Avg_price_per_ltr": 'Сеть',
  "Avg_price_per_qty": 'Сеть',
  "val_rur": 'Сеть',
  "vol_qty": 'Сеть',
  "vol_ltr": 'Сеть',
  "base": 'Сеть',
  "Repeaters_share": 'Сеть',
  "Closure_rate": 'Сеть',
  "Share_of_requirment": 'Сеть',
  "Traffic": 'Сеть',
}